### ISSUE TITLE
Put on a killer event

### ISSUE THREAD

**Issue by mattdsteele** [sbuscher/cunningham-cx#9]
You can probably mark this one done :)

Thanks again for all the work you, Todd, and the rest of the team put on to bring CX back to Nebraska. Looking forward to this being the start of a new era!

**Comment by sbuscher** [comment]
Oh I see you've found another one of my abandoned repos! I'm still mesmerized how well things went yesterday. Never thought we'd get the turnout. Race went smooth and riders and fans were enjoying themselves. Can't beat that. Thanks also for volunteering your time. I hope that the momentum continues into next weekend. I just saw the $20 gift card at trek for each registrant. That is fantastic!
